####################
####  Settings  ####
####################

font-family = "JetBrainsMono NFM Regular"
background-opacity = 0.99
theme = TokyoNight
font-size = 12
adjust-cell-height = 4
window-padding-balance = true
window-decoration = none
keybind = global:cmd+backquote=toggle_quick_terminal

